// Copyright 2013 Reid Netterville III 
gtrSTD_opal=[
"<tt>",
"Opal",
" ",
"n0",
"CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____",
"FePb HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____",
"AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____ CuHg PbFe ____",
"SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____",
"AgAu ____ FePb HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____",
"CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____",
" ",
"j5",
"AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____ AuSn ____",
"CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____",
"____ ____ SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi",
"AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____",
"SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____",
"AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____ AuSn ____",
" ",
"k34",
"____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____",
"CuPb PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____",
"HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe FeTi",
"AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____",
"SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____",
"____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____",
" ",
"j5y6",
"AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____",
"CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____",
"HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi",
"AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____",
"____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____",
"AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____",
" ",
"k34x2",
"AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____",
"CuPb PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____",
"HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe FeTi",
"____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____",
"SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____",
"AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____",
" ",
"k1",
"SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____",
"AgPb ____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____",
"PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe ____",
"HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr",
"AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____",
"SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____",
" ",
"j2k34",
"____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____",
"AgPb TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____ AuAu ____",
"PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe CuTi",
"____ ____ ____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn",
"AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____",
"____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____",
" ",
"n25x6",
"____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____",
"AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____",
"PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi",
"HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn",
"____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____",
"____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____",
" ",
"j25y6",
"SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____",
"AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____ ____ ____",
"PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi",
"____ ____ SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn",
"____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____",
"SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____",
" ",
"k5",
"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____",
"SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____",
"____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe ____",
"PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ____",
"HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ____ FeNp",
"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____",
" ",
"k15",
"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____",
"SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____",
"____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe ____",
"PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____ CuUr",
"HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ____ FeNp",
"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____",
" ",
"j56",
"AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ____ PbSn ____",
"SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____",
"____ FeNp ____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi",
"PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ____",
"____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp",
"AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ____ PbSn ____",
" ",
"k135x4",
"____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____",
"SnPb ____ CuUr PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____",
"TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe ____",
"PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr",
"HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe ____ TiAg FeNp",
"____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____",
" ",
"j56y7",
"AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ____ PbSn ____",
"____ UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____",
"____ FeNp HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe AgTi",
"PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ____",
"HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp",
"AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ____ PbSn ____",
" ",
"n345y7",
"AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____",
"SnPb ____ CuUr ____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____",
"TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe ____",
"____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr",
"HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe ____ TiAg FeNp",
"AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____",
" ",
"k1j6y7",
"AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____",
"____ ____ CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____",
"TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe ____",
"PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____ CuUr",
"HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp",
"AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____",
" ",
"k345x2",
"AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ____ ____",
"SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____",
"____ FeNp HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe AgTi",
"____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ____",
"HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ____ FeNp",
"AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ____ ____",
" ",
"k2j56y7",
"HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ____ ____ FePu",
"____ NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____",
"____ CuNp PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe SnTi",
"____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ____",
"PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp",
"HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ____ ____ FePu",
" ",
"j346y5",
"HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu",
"AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____",
"____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe ____",
"TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu ____",
"____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp",
"HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu",
" ",
"j3k5",
"____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu",
"AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____",
"____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe ____",
"TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____",
"PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____ CuNp",
"____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu",
" ",
"n167",
"____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu",
"AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____ CuNp PbAu ____",
"____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe SnTi",
"____ FePu ____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ____",
"PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____ CuNp",
"____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu",
" ",
"k2",
"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePb",
"AuPb NpCu ____ ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____",
"UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____",
"____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ____",
"PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ UrAg ____",
"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePu",
" ",
"k25",
"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePb",
"AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____",
"____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____",
"____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____",
"PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____ CuNp",
"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu",
" ",
"k125",
"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu",
"AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____",
"____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____",
"____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ AgUr",
"PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____ CuNp",
"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu",
" ",
"k12",
"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu",
"AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____",
"UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____",
"____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ AgUr",
"PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg ____",
"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu",
" ",
"k12j5",
"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ AgUr ____ FePu",
"AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____",
"____ ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe SnTi",
"____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ AgUr",
"PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____ ____",
"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ AgUr ____ FePu",
" ",
"k2x1",
"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu",
"AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____",
"UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____",
"TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ____",
"PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg ____",
"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu",
" ",
"k2j5",
"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ____ ____ FePu",
"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____",
"____ ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi",
"____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ____",
"PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ ____",
"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ____ ____ FePu",
" ",
"k25x1",
"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu",
"AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____",
"____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____",
"TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ____",
"PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____ CuNp",
"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu",
" ",
"k2j56",
"HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ____ ____ FePu",
"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp ____ ____",
"____ CuNp ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi",
"____ FePu HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ____",
"____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp",
"HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ____ ____ FePu",
" ",
"k257x1",
"HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu",
"____ NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____",
"____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe ____",
"TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu ____",
"PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp",
"HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu",
" ",
"k25x17",
"HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu",
"____ ____ AgUr TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____",
"____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe ____",
"TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____ AgUr",
"PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe ____ ____ CuNp",
"HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu",
" ",
"k2j5y6",
"HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu",
"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg ____ ____ ____",
"UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi",
"____ FePu HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ____",
"____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg ____",
"HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu",
" ",
"k2j5x1",
"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ____ TiSn FePu",
"AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____",
"____ ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe SnTi",
"TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ____",
"PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____ ____",
"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ____ TiSn FePu",
" ",
"k1j5",
"TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr NpSn ____",
"PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____ ____ UrAu ____",
"____ ____ UrAu ____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi",
"NpSn ____ TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr",
"UrAu ____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____ ____",
"TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr NpSn ____",
" ",
"n67x2",
"TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ____ ____",
"PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____ SnNp UrAu ____",
"____ SnNp UrAu ____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi",
"____ ____ TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr",
"UrAu ____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____ SnNp",
"TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ____ ____",
" ",
"j2k5",
"MnHg CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____",
"TiPb FeCu HgMn ____ ____ MnHg CuFe ____ ____ AuNp NpAu ____",
"____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe ____",
"____ ____ MnHg CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn",
"NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe ____ ____ AuNp",
"MnHg CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____",
" ",
"n6x2",
"MnHg CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____ ____",
"____ FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp NpAu ____",
"____ AuNp NpAu ____ ____ FeCu HgMn ____ ____ MnHg CuFe PbTi",
"____ ____ MnHg CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn",
"NpAu ____ ____ FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp",
"MnHg CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____ ____",
" ",
"j25",
"MnHg CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____ ____",
"TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ____ NpAu ____",
"____ ____ NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi",
"____ ____ MnHg CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn",
"NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ____",
"MnHg CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____ ____",
" ",
"j256",
"MnHg CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____ ____",
"TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ____ ____",
"____ AuNp ____ ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi",
"____ ____ MnHg CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn",
"____ ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp",
"MnHg CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____ ____",
" ",
" ",
"Copyright &#169; 2013 Reid Netterville III",
"</tt>"];
for(var i=0;i<gtrSTD_opal.length;i++){document.write(gtrSTD_opal[i]+"<br>");}
// var i=0;while(gtrSTD_opal[i]){document.write(gtrSTD_opal[i]+"<br>");i++;}