// Copyright 2013-2018 Reid Netterville III 

"use strict";

gtrSTD_topaz=[
"<pre>",
"Topaz",
" ",
"n0",
"CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____",
"FePb HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____",
"AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____ CuHg PbFe ____",
"SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____",
"AgAu ____ FePb HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____",
"CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____",
" ",
"k6",
"CuPb PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____",
"FeTi HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe",
"AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____",
"SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____",
"____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____",
"CuPb PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____",
" ",
"j17",
"CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____",
"FeTi ____ ____ SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe",
"AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____",
"SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____",
"AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____ AuSn ____",
"CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____",
" ",
"k6x5",
"CuPb PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____",
"FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe",
"____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____",
"SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____",
"AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____",
"CuPb PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____",
" ",
"j17y2",
"CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____",
"FeTi HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe",
"AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____",
"____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____",
"AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____",
"CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____",
" ",
"j3",
"____ PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe",
"FeUr HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____",
"AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____",
"SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____",
"AgPb ____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____",
"____ PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe",
" ",
"j34k6",
"CuTi ____ ____ AuAu ____ ____ TiCu FeMn HgSn ____ SnHg MnFe",
"FeMn HgSn ____ SnHg MnFe CuTi ____ ____ AuAu ____ ____ TiCu",
"AuAu ____ ____ TiCu FeMn HgSn ____ SnHg MnFe CuTi ____ ____",
"SnHg MnFe CuTi ____ ____ AuAu ____ ____ TiCu FeMn HgSn ____",
"____ TiCu FeMn HgSn ____ SnHg MnFe CuTi ____ ____ AuAu ____",
"CuTi ____ ____ AuAu ____ ____ TiCu FeMn HgSn ____ SnHg MnFe",
" ",
"j17k2",
"CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe",
"FeMn ____ ____ ____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu",
"AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____",
"____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____",
"AgPb TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____ AuAu ____",
"CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe",
" ",
"n26y5",
"CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe",
"FeMn ____ ____ SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu",
"____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____",
"SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____",
"AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____ ____ ____",
"CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe",
" ",
"k26x5",
"CuTi PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe",
"FeMn HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu",
"____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____",
"____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____",
"AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____",
"CuTi PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe",
" ",
"j6",
"CuUr PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____",
"FeNp HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ____",
"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____",
"SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____",
"____ ____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe",
"CuUr PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____",
" ",
"j36",
"____ PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu",
"FeNp HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ____",
"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____",
"SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____",
"____ ____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe",
"____ PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu",
" ",
"k56",
"CuUr PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____",
"FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe ____ TiAg",
"____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____",
"SnPb ____ CuUr PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____",
"____ TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe",
"CuUr PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____",
" ",
"j136y7",
"____ PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu",
"FeNp ____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ____",
"AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ____ PbSn ____",
"SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____",
"AgTi ____ FeNp ____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe",
"____ PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu",
" ",
"k56x4",
"CuUr ____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____",
"FeNp HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe ____ TiAg",
"AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____",
"SnPb ____ CuUr ____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____",
"____ TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe",
"CuUr ____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____",
" ",
"n167x4",
"____ PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu",
"FeNp HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe AgTi ____",
"AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ____ PbSn ____",
"____ UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____",
"AgTi ____ FeNp HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe",
"____ PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu",
" ",
"j3k5x4",
"____ ____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu",
"FeNp HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ____",
"AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ____ ____",
"SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____",
"AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe",
"____ ____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu",
" ",
"j167y2",
"CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____",
"FeNp HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe ____ TiAg",
"AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____",
"____ ____ CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____",
"____ TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe",
"CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____",
" ",
"j2k56x4",
"CuNp ____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____",
"FePu HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu ____ TiSn",
"AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____",
"____ ____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe",
"____ TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu",
"CuNp ____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____",
" ",
"k157x6",
"CuNp PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe SnTi ____",
"FePu HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ____ ____",
"____ NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____",
"SnTi ____ CuNp PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe",
"____ ____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu",
"CuNp PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe SnTi ____",
" ",
"k1j6",
"CuNp PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____",
"FePu ____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ____",
"AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____ CuNp PbAu ____",
"SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe",
"____ ____ FePu ____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu",
"CuNp PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____",
" ",
"n345",
"CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____",
"FePu ____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ TiSn",
"AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____",
"____ ____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe",
"____ TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu",
"CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____",
" ",
"j2",
"CuNp PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____",
"FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ AgUr ____",
"AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____",
"____ ____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe",
"AgUr ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____",
"CuNp PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____",
" ",
"j26",
"CuNp PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____",
"FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ ____",
"AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____",
"____ ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe",
"____ ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu",
"CuNp PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____",
" ",
"j236",
"____ PbAu ____ AuPb NpCu ____ ____ FePb HgHg PuFe ____ UrAg",
"FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ____ ____",
"AuPb NpCu ____ ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____",
"____ UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe",
"____ ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu",
"____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ UrAg",
" ",
"j23",
"____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg",
"FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ AgUr ____",
"AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____",
"____ UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe",
"AgUr ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____",
"____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg",
" ",
"j23k6",
"____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg",
"FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ____ TiSn",
"AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____",
"____ UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe",
"____ TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____",
"____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg",
" ",
"j2y3",
"____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____",
"FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ AgUr ____",
"AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____",
"SnTi ____ ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe",
"AgUr ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____",
"____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____",
" ",
"j2k6",
"CuNp PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____",
"FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ____ TiSn",
"AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____",
"____ ____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe",
"____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____",
"CuNp PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____",
" ",
"j26y3",
"____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____",
"FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ____ ____",
"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____",
"SnTi ____ ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe",
"____ ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu",
"____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____",
" ",
"j2k56",
"CuNp PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe ____ ____",
"FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu ____ TiSn",
"____ NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____",
"____ ____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe",
"____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu",
"CuNp PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe ____ ____",
" ",
"j246y3",
"CuNp ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____",
"FePu HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ____ ____",
"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp ____ ____",
"SnTi ____ CuNp ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe",
"____ ____ FePu HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu",
"CuNp ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____",
" ",
"j26y34",
"____ ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg",
"FePu HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ____ ____",
"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg ____ ____ ____",
"SnTi UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe",
"____ ____ FePu HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu",
"____ ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg",
" ",
"j2k6x5",
"CuNp PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe ____ ____",
"FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____ AgUr TiSn",
"____ ____ AgUr TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____",
"____ ____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe",
"AgUr TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____",
"CuNp PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe ____ ____",
" ",
"j2k6y3",
"____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____",
"FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ____ TiSn",
"AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____",
"SnTi ____ ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe",
"____ TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____",
"____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____",
" ",
"j3k6",
"____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____ SnNp UrAu",
"FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ____ ____ TiHg",
"AuUr ____ ____ TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____",
"SnNp UrAu ____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____",
"____ TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ____",
"____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____ SnNp UrAu",
" ",
"n45y2",
"____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____ ____ UrAu",
"FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr NpSn ____ TiHg",
"AuUr NpSn ____ TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____",
"____ UrAu ____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____",
"____ TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr NpSn",
"____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____ ____ UrAu",
" ",
"k2j6",
"CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____ ____ MnHg",
"FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp NpAu ____ ____",
"AuNp NpAu ____ ____ FeCu HgMn ____ ____ MnHg CuFe PbTi ____",
"____ MnHg CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____",
"____ ____ FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp NpAu",
"CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____ ____ MnHg",
" ",
"n5y2",
"CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____ MnHg",
"FeCu HgMn ____ ____ MnHg CuFe ____ ____ AuNp NpAu ____ TiPb",
"AuNp NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe ____ ____",
"____ MnHg CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____",
"____ TiPb FeCu HgMn ____ ____ MnHg CuFe ____ ____ AuNp NpAu",
"CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____ MnHg",
" ",
"k26",
"CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____ ____ MnHg",
"FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ____ ____ TiPb",
"AuNp ____ ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____",
"____ MnHg CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____",
"____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ____",
"CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____ ____ MnHg",
" ",
"k256",
"CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____ ____ MnHg",
"FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ____ NpAu ____ TiPb",
"____ NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____",
"____ MnHg CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____",
"____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ____ NpAu",
"CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____ ____ MnHg",
" ",
" ",
"Copyright \u00A9 2013-2018 Reid Netterville III",
"<\/pre>"];

for (var i = 0; i < gtrSTD_topaz.length; i++) {
  document.writeln(gtrSTD_topaz[i]);
}

