// Copyright 2013-2015 Reid Netterville III 

mdlSTD_topaz=[
"<pre>",
"Topaz",
" ",
"n0",
"CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____",
"AgAu ____ FePb HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____",
"SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____",
"AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____ CuHg PbFe ____",
" ",
"k6",
"CuPb PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____",
"____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____",
"SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____",
"AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____",
" ",
"j17",
"CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____",
"AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____ AuSn ____",
"SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____",
"AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____",
" ",
"k6x5",
"CuPb PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____",
"AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____",
"SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____",
"____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____",
" ",
"j17y2",
"CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____",
"AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____",
"____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____",
"AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____",
" ",
"j3",
"____ PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe",
"AgPb ____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____",
"SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____",
"AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____",
" ",
"j34k6",
"CuTi ____ ____ AuAu ____ ____ TiCu FeMn HgSn ____ SnHg MnFe",
"____ TiCu FeMn HgSn ____ SnHg MnFe CuTi ____ ____ AuAu ____",
"SnHg MnFe CuTi ____ ____ AuAu ____ ____ TiCu FeMn HgSn ____",
"AuAu ____ ____ TiCu FeMn HgSn ____ SnHg MnFe CuTi ____ ____",
" ",
"j17k2",
"CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe",
"AgPb TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____ AuAu ____",
"____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____",
"AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____",
" ",
"n26y5",
"CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe",
"AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____ ____ ____",
"SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____",
"____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____",
" ",
"k26x5",
"CuTi PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe",
"AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____",
"____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____",
"____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____",
" ",
"j6",
"CuUr PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____",
"____ ____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe",
"SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____",
"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____",
" ",
"j36",
"____ PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu",
"____ ____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe",
"SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____",
"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____",
" ",
"k56",
"CuUr PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____",
"____ TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe",
"SnPb ____ CuUr PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____",
"____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____",
" ",
"j136y7",
"____ PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu",
"AgTi ____ FeNp ____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe",
"SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____",
"AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ____ PbSn ____",
" ",
"k56x4",
"CuUr ____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____",
"____ TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe",
"SnPb ____ CuUr ____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____",
"AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____",
" ",
"n167x4",
"____ PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu",
"AgTi ____ FeNp HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe",
"____ UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____",
"AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ____ PbSn ____",
" ",
"j3k5x4",
"____ ____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu",
"AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe",
"SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____",
"AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ____ ____",
" ",
"j167y2",
"CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____",
"____ TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe",
"____ ____ CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____",
"AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____",
" ",
"j2k56x4",
"CuNp ____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____",
"____ TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu",
"____ ____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe",
"AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____",
" ",
"k157x6",
"CuNp PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe SnTi ____",
"____ ____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu",
"SnTi ____ CuNp PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe",
"____ NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____",
" ",
"k1j6",
"CuNp PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____",
"____ ____ FePu ____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu",
"SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe",
"AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____ CuNp PbAu ____",
" ",
"n345",
"CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____",
"____ TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu",
"____ ____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe",
"AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____",
" ",
"j2",
"CuNp PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____",
"AgUr ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____",
"____ ____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe",
"AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____",
" ",
"j26",
"CuNp PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____",
"____ ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu",
"____ ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe",
"AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____",
" ",
"j236",
"____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ UrAg",
"____ ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu",
"____ UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe",
"AuPb NpCu ____ ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____",
" ",
"j23",
"____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg",
"AgUr ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____",
"____ UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe",
"AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____",
" ",
"j23k6",
"____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg",
"____ TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____",
"____ UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe",
"AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____",
" ",
"j2y3",
"____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____",
"AgUr ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____",
"SnTi ____ ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe",
"AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____",
" ",
"j2k6",
"CuNp PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____",
"____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____",
"____ ____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe",
"AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____",
" ",
"j26y3",
"____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____",
"____ ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu",
"SnTi ____ ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe",
"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____",
" ",
"j2k56",
"CuNp PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe ____ ____",
"____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu",
"____ ____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe",
"____ NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____",
" ",
"j246y3",
"CuNp ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____",
"____ ____ FePu HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu",
"SnTi ____ CuNp ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe",
"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp ____ ____",
" ",
"j26y34",
"____ ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg",
"____ ____ FePu HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu",
"SnTi UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe",
"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg ____ ____ ____",
" ",
"j2k6x5",
"CuNp PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe ____ ____",
"AgUr TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____",
"____ ____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe",
"____ ____ AgUr TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____",
" ",
"j2k6y3",
"____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____",
"____ TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____",
"SnTi ____ ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe",
"AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____",
" ",
"j3k6",
"____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____ SnNp UrAu",
"____ TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ____",
"SnNp UrAu ____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____",
"AuUr ____ ____ TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____",
" ",
"n45y2",
"____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____ ____ UrAu",
"____ TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr NpSn",
"____ UrAu ____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____",
"AuUr NpSn ____ TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____",
" ",
"k2j6",
"CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____ ____ MnHg",
"____ ____ FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp NpAu",
"____ MnHg CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____",
"AuNp NpAu ____ ____ FeCu HgMn ____ ____ MnHg CuFe PbTi ____",
" ",
"n5y2",
"CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____ MnHg",
"____ TiPb FeCu HgMn ____ ____ MnHg CuFe ____ ____ AuNp NpAu",
"____ MnHg CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____",
"AuNp NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe ____ ____",
" ",
"k26",
"CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____ ____ MnHg",
"____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ____",
"____ MnHg CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____",
"AuNp ____ ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____",
" ",
"k256",
"CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____ ____ MnHg",
"____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ____ NpAu",
"____ MnHg CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____",
"____ NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____",
" ",
" ",
"Copyright \u00A9 2013-2015 Reid Netterville III",
"<\/pre>"];

for (var i = 0; i < mdlSTD_topaz.length; i++) {
  document.writeln(mdlSTD_topaz[i]);
}

