// Copyright 2013 Reid Netterville III 
mdlSTD_opal=[
"<tt>",
"Opal",
" ",
"n0",
"CuMg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____",
"AgAu ____ FePb HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____",
"SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____",
"AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____ CuHg PbFe ____",
" ",
"j5",
"AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____ AuSn ____",
"SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____",
"AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____",
"____ ____ SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi",
" ",
"k34",
"____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____",
"SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____",
"AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____",
"HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe FeTi",
" ",
"j5y6",
"AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____",
"____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____",
"AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____",
"HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi",
" ",
"k34x2",
"AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____",
"SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____",
"____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____",
"HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe FeTi",
" ",
"k1",
"SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____",
"AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____",
"HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr",
"PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe ____",
" ",
"j2k34",
"____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____",
"AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____",
"____ ____ ____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn",
"PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe CuTi",
" ",
"n25x6",
"____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____",
"____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____",
"HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn",
"PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi",
" ",
"j25y6",
"SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____",
"____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____",
"____ ____ SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn",
"PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi",
" ",
"k5",
"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____",
"HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ____ FeNp",
"PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ____",
"____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe ____",
" ",
"k15",
"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____",
"HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ____ FeNp",
"PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____ CuUr",
"____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe ____",
" ",
"j56",
"AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ____ PbSn ____",
"____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp",
"PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ____",
"____ FeNp ____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi",
" ",
"k135x4",
"____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____",
"HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe ____ TiAg FeNp",
"PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr",
"TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe ____",
" ",
"j56y7",
"AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ____ PbSn ____",
"HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp",
"PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ____",
"____ FeNp HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe AgTi",
" ",
"n345y7",
"AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____",
"HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe ____ TiAg FeNp",
"____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr",
"TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe ____",
" ",
"k1j6y7",
"AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____",
"HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp",
"PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____ CuUr",
"TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe ____",
" ",
"k345x2",
"AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ____ ____",
"HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ____ FeNp",
"____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ____",
"____ FeNp HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe AgTi",
" ",
"k2j56y7",
"HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ____ ____ FePu",
"PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp",
"____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ____",
"____ CuNp PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe SnTi",
" ",
"j346y5",
"HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu",
"____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp",
"TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu ____",
"____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe ____",
" ",
"j3k5",
"____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu",
"PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____ CuNp",
"TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____",
"____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe ____",
" ",
"n167",
"____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu",
"PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____ CuNp",
"____ FePu ____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ____",
"____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe SnTi",
" ",
"k2",
"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePu",
"PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ UrAg ____",
"____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ____",
"UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____",
" ",
"k25",
"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu",
"PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____ CuNp",
"____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____",
"____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____",
" ",
"k125",
"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu",
"PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____ CuNp",
"____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ AgUr",
"____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____",
" ",
"k12",
"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu",
"PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg ____",
"____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ AgUr",
"UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____",
" ",
"k12j5",
"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ AgUr ____ FePu",
"PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____ ____",
"____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ AgUr",
"____ ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe SnTi",
" ",
"k2x1",
"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu",
"PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg ____",
"TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ____",
"UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____",
" ",
"k2j5",
"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ____ ____ FePu",
"PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ ____",
"____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ____",
"____ ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi",
" ",
"k25x1",
"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu",
"PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____ CuNp",
"TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ____",
"____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____",
" ",
"k2j56",
"HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ____ ____ FePu",
"____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp",
"____ FePu HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ____",
"____ CuNp ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi",
" ",
"k257x1",
"HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu",
"PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp",
"TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu ____",
"____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe ____",
" ",
"k25x17",
"HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu",
"PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe ____ ____ CuNp",
"TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____ AgUr",
"____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe ____",
" ",
"k2j5y6",
"HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu",
"____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg ____",
"____ FePu HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ____",
"UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi",
" ",
"k2j5x1",
"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ____ TiSn FePu",
"PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____ ____",
"TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ____",
"____ ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe SnTi",
" ",
"k1j5",
"TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr NpSn ____",
"UrAu ____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____ ____",
"NpSn ____ TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr",
"____ ____ UrAu ____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi",
" ",
"n67x2",
"TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ____ ____",
"UrAu ____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____ SnNp",
"____ ____ TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr",
"____ SnNp UrAu ____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi",
" ",
"j2k5",
"MnHg CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____",
"NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe ____ ____ AuNp",
"____ ____ MnHg CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn",
"____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe ____",
" ",
"n6x2",
"MnHg CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____ ____",
"NpAu ____ ____ FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp",
"____ ____ MnHg CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn",
"____ AuNp NpAu ____ ____ FeCu HgMn ____ ____ MnHg CuFe PbTi",
" ",
"j25",
"MnHg CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____ ____",
"NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ____",
"____ ____ MnHg CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn",
"____ ____ NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi",
" ",
"j256",
"MnHg CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____ ____",
"____ ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp",
"____ ____ MnHg CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn",
"____ AuNp ____ ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi",
" ",
" ",
"Copyright &#169; 2013 Reid Netterville III",
"</tt>"];
for(var i=0;i<mdlSTD_opal.length;i++){document.write(mdlSTD_opal[i]+"<br>");}
// var i=0;while(mdlSTD_opal[i]){document.write(mdlSTD_opal[i]+"<br>");i++;}