// Copyright 2015-2018 Reid Netterville III 

"use strict";

var QualitativE = [

 {"$T":"n0",
  "nF":"PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____ CuHg ",
  "nC":"HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____ FePb ",
  "nG":"AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____ CuHg PbFe ____ ",
  "nD":"SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____ ",
  "nA":"AgAu ____ FePb HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____ ",
  "nE":"CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____ ",
  "nB":"FePb HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____ "},

 {"$T":"k6",
  "nF":"PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____ CuPb ",
  "nC":"HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe FeTi ",
  "nG":"AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ",
  "nD":"SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____ ",
  "nA":"____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____ ",
  "nE":"CuPb PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____ ",
  "nB":"FeTi HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe "},

 {"$T":"j17",
  "nF":"PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____ CuPb ",
  "nC":"____ ____ SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ",
  "nG":"AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____ ",
  "nD":"SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____ ",
  "nA":"AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____ AuSn ____ ",
  "nE":"CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____ ",
  "nB":"FeTi ____ ____ SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe "},

 {"$T":"k6x5",
  "nF":"PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb ",
  "nC":"HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe FeTi ",
  "nG":"____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ",
  "nD":"SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____ ",
  "nA":"AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____ ",
  "nE":"CuPb PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____ ",
  "nB":"FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe "},

 {"$T":"j17y2",
  "nF":"PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____ CuPb ",
  "nC":"HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ",
  "nG":"AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____ ",
  "nD":"____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____ ",
  "nA":"AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____ ",
  "nE":"CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____ ",
  "nB":"FeTi HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe "},

 {"$T":"j3",
  "nF":"PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe ____ ",
  "nC":"HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr ",
  "nG":"AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____ ",
  "nD":"SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____ ",
  "nA":"AgPb ____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____ ",
  "nE":"____ PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe ",
  "nB":"FeUr HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ "},

 {"$T":"j34k6",
  "nF":"____ ____ AuAu ____ ____ TiCu FeMn HgSn ____ SnHg MnFe CuTi ",
  "nC":"HgSn ____ SnHg MnFe CuTi ____ ____ AuAu ____ ____ TiCu FeMn ",
  "nG":"AuAu ____ ____ TiCu FeMn HgSn ____ SnHg MnFe CuTi ____ ____ ",
  "nD":"SnHg MnFe CuTi ____ ____ AuAu ____ ____ TiCu FeMn HgSn ____ ",
  "nA":"____ TiCu FeMn HgSn ____ SnHg MnFe CuTi ____ ____ AuAu ____ ",
  "nE":"CuTi ____ ____ AuAu ____ ____ TiCu FeMn HgSn ____ SnHg MnFe ",
  "nB":"FeMn HgSn ____ SnHg MnFe CuTi ____ ____ AuAu ____ ____ TiCu "},

 {"$T":"j17k2",
  "nF":"PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe CuTi ",
  "nC":"____ ____ ____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ",
  "nG":"AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____ ",
  "nD":"____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____ ",
  "nA":"AgPb TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____ AuAu ____ ",
  "nE":"CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe ",
  "nB":"FeMn ____ ____ ____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu "},

 {"$T":"n26y5",
  "nF":"PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi ",
  "nC":"____ ____ SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ",
  "nG":"____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____ ",
  "nD":"SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____ ",
  "nA":"AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____ ____ ____ ",
  "nE":"CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe ",
  "nB":"FeMn ____ ____ SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu "},

 {"$T":"k26x5",
  "nF":"PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi ",
  "nC":"HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ",
  "nG":"____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____ ",
  "nD":"____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____ ",
  "nA":"AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____ ",
  "nE":"CuTi PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe ",
  "nB":"FeMn HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu "},

 {"$T":"j6",
  "nF":"PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____ CuUr ",
  "nC":"HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ____ FeNp ",
  "nG":"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ",
  "nD":"SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ ",
  "nA":"____ ____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe ",
  "nE":"CuUr PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____ ",
  "nB":"FeNp HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ____ "},

 {"$T":"j36",
  "nF":"PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ____ ",
  "nC":"HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ____ FeNp ",
  "nG":"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____ ",
  "nD":"SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ ",
  "nA":"____ ____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe ",
  "nE":"____ PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ",
  "nB":"FeNp HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ____ "},

 {"$T":"k56",
  "nF":"PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr ",
  "nC":"HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe ____ TiAg FeNp ",
  "nG":"____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ",
  "nD":"SnPb ____ CuUr PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____ ",
  "nA":"____ TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe ",
  "nE":"CuUr PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____ ",
  "nB":"FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe ____ TiAg "},

 {"$T":"j136y7",
  "nF":"PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ____ ",
  "nC":"____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ",
  "nG":"AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ____ PbSn ____ ",
  "nD":"SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____ ",
  "nA":"AgTi ____ FeNp ____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe ",
  "nE":"____ PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ",
  "nB":"FeNp ____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ____ "},

 {"$T":"k56x4",
  "nF":"____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr ",
  "nC":"HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe ____ TiAg FeNp ",
  "nG":"AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____ ",
  "nD":"SnPb ____ CuUr ____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____ ",
  "nA":"____ TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe ",
  "nE":"CuUr ____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____ ",
  "nB":"FeNp HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe ____ TiAg "},

 {"$T":"n167x4",
  "nF":"PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ____ ",
  "nC":"HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ",
  "nG":"AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ____ PbSn ____ ",
  "nD":"____ UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____ ",
  "nA":"AgTi ____ FeNp HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe ",
  "nE":"____ PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ",
  "nB":"FeNp HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe AgTi ____ "},

 {"$T":"j3k5x4",
  "nF":"____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ",
  "nC":"HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ____ FeNp ",
  "nG":"AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ____ ____ ",
  "nD":"SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____ ",
  "nA":"AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe ",
  "nE":"____ ____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ",
  "nB":"FeNp HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ____ "},

 {"$T":"j167y2",
  "nF":"PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____ CuUr ",
  "nC":"HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp ",
  "nG":"AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____ ",
  "nD":"____ ____ CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____ ",
  "nA":"____ TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe ",
  "nE":"CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____ ",
  "nB":"FeNp HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe ____ TiAg "},

 {"$T":"j2k56x4",
  "nF":"____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp ",
  "nC":"HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu ",
  "nG":"AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____ ",
  "nD":"____ ____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe ",
  "nA":"____ TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu ",
  "nE":"CuNp ____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____ ",
  "nB":"FePu HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu ____ TiSn "},

 {"$T":"k157x6",
  "nF":"PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp ",
  "nC":"HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ____ ____ FePu ",
  "nG":"____ NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____ ",
  "nD":"SnTi ____ CuNp PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe ",
  "nA":"____ ____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ",
  "nE":"CuNp PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe SnTi ____ ",
  "nB":"FePu HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ____ ____ "},

 {"$T":"k1j6",
  "nF":"PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____ CuNp ",
  "nC":"____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ",
  "nG":"AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____ CuNp PbAu ____ ",
  "nD":"SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe ",
  "nA":"____ ____ FePu ____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ",
  "nE":"CuNp PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____ ",
  "nB":"FePu ____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ____ "},

 {"$T":"n345",
  "nF":"PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____ CuNp ",
  "nC":"____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ",
  "nG":"AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____ ",
  "nD":"____ ____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe ",
  "nA":"____ TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ",
  "nE":"CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____ ",
  "nB":"FePu ____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ TiSn "},

 {"$T":"j2",
  "nF":"PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____ CuNp ",
  "nC":"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu ",
  "nG":"AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ ",
  "nD":"____ ____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ",
  "nA":"AgUr ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ",
  "nE":"CuNp PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____ ",
  "nB":"FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ AgUr ____ "},

 {"$T":"j26",
  "nF":"PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____ CuNp ",
  "nC":"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ",
  "nG":"AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ ",
  "nD":"____ ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ",
  "nA":"____ ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ",
  "nE":"CuNp PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____ ",
  "nB":"FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ ____ "},

 {"$T":"j236",
  "nF":"PbAu ____ AuPb NpCu ____ ____ FePb HgHg PuFe ____ UrAg ____ ",
  "nC":"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePu ",
  "nG":"AuPb NpCu ____ ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ ",
  "nD":"____ UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ",
  "nA":"____ ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ",
  "nE":"____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ UrAg ",
  "nB":"FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ____ ____ "},

 {"$T":"j23",
  "nF":"PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg ____ ",
  "nC":"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu ",
  "nG":"AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ ",
  "nD":"____ UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ",
  "nA":"AgUr ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ",
  "nE":"____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg ",
  "nB":"FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ AgUr ____ "},

 {"$T":"j23k6",
  "nF":"PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg ____ ",
  "nC":"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu ",
  "nG":"AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____ ",
  "nD":"____ UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ",
  "nA":"____ TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ",
  "nE":"____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg ",
  "nB":"FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ____ TiSn "},

 {"$T":"j2y3",
  "nF":"PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____ ____ ",
  "nC":"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ AgUr ____ FePu ",
  "nG":"AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ ",
  "nD":"SnTi ____ ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ",
  "nA":"AgUr ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ",
  "nE":"____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____ ",
  "nB":"FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ AgUr ____ "},

 {"$T":"j2k6",
  "nF":"PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____ CuNp ",
  "nC":"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu ",
  "nG":"AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ",
  "nD":"____ ____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ",
  "nA":"____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ",
  "nE":"CuNp PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____ ",
  "nB":"FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ____ TiSn "},

 {"$T":"j26y3",
  "nF":"PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ ____ ",
  "nC":"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ____ ____ FePu ",
  "nG":"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ ",
  "nD":"SnTi ____ ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ",
  "nA":"____ ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ",
  "nE":"____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ ",
  "nB":"FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ____ ____ "},

 {"$T":"j2k56",
  "nF":"PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp ",
  "nC":"HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu ",
  "nG":"____ NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ",
  "nD":"____ ____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe ",
  "nA":"____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu ",
  "nE":"CuNp PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe ____ ____ ",
  "nB":"FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu ____ TiSn "},

 {"$T":"j246y3",
  "nF":"____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp ",
  "nC":"HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ____ ____ FePu ",
  "nG":"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp ____ ____ ",
  "nD":"SnTi ____ CuNp ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe ",
  "nA":"____ ____ FePu HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ",
  "nE":"CuNp ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ ",
  "nB":"FePu HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ____ ____ "},

 {"$T":"j26y34",
  "nF":"____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg ____ ",
  "nC":"HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu ",
  "nG":"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg ____ ____ ____ ",
  "nD":"SnTi UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe ",
  "nA":"____ ____ FePu HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ",
  "nE":"____ ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg ",
  "nB":"FePu HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ____ ____ "},

 {"$T":"j2k6x5",
  "nF":"PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe ____ ____ CuNp ",
  "nC":"HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu ",
  "nG":"____ ____ AgUr TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ",
  "nD":"____ ____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe ",
  "nA":"AgUr TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____ ",
  "nE":"CuNp PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe ____ ____ ",
  "nB":"FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____ AgUr TiSn "},

 {"$T":"j2k6y3",
  "nF":"PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____ ____ ",
  "nC":"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ____ TiSn FePu ",
  "nG":"AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____ ",
  "nD":"SnTi ____ ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ",
  "nA":"____ TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ",
  "nE":"____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____ ",
  "nB":"FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ____ TiSn "},

 {"$T":"j3k6",
  "nF":"PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____ SnNp UrAu ____ ",
  "nC":"HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ____ ____ TiHg FeFe ",
  "nG":"AuUr ____ ____ TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____ ",
  "nD":"SnNp UrAu ____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____ ",
  "nA":"____ TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ____ ",
  "nE":"____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____ SnNp UrAu ",
  "nB":"FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ____ ____ TiHg "},

 {"$T":"n45y2",
  "nF":"PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____ ____ UrAu ____ ",
  "nC":"HgTi ____ ____ UrAu ____ PbPb ____ AuUr NpSn ____ TiHg FeFe ",
  "nG":"AuUr NpSn ____ TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____ ",
  "nD":"____ UrAu ____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____ ",
  "nA":"____ TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr NpSn ",
  "nE":"____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____ ____ UrAu ",
  "nB":"FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr NpSn ____ TiHg "},

 {"$T":"j3k56x4",
  "nF":"____ ____ AuUr NpSn ____ TiHg FeFe HgTi ____ SnNp UrAu ____ ",
  "nC":"HgTi ____ SnNp UrAu ____ ____ ____ AuUr NpSn ____ TiHg FeFe ",
  "nG":"AuUr NpSn ____ TiHg FeFe HgTi ____ SnNp UrAu ____ ____ ____ ",
  "nD":"SnNp UrAu ____ ____ ____ AuUr NpSn ____ TiHg FeFe HgTi ____ ",
  "nA":"____ TiHg FeFe HgTi ____ SnNp UrAu ____ ____ ____ AuUr NpSn ",
  "nE":"____ ____ ____ AuUr NpSn ____ TiHg FeFe HgTi ____ SnNp UrAu ",
  "nB":"FeFe HgTi ____ SnNp UrAu ____ ____ ____ AuUr NpSn ____ TiHg "},

 {"$T":"k2j6",
  "nF":"PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____ ____ MnHg CuFe ",
  "nC":"HgMn ____ ____ MnHg CuFe PbTi ____ AuNp NpAu ____ ____ FeCu ",
  "nG":"AuNp NpAu ____ ____ FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ",
  "nD":"____ MnHg CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____ ",
  "nA":"____ ____ FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp NpAu ",
  "nE":"CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____ ____ MnHg ",
  "nB":"FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp NpAu ____ ____ "},

 {"$T":"n5y2",
  "nF":"____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe ",
  "nC":"HgMn ____ ____ MnHg CuFe ____ ____ AuNp NpAu ____ TiPb FeCu ",
  "nG":"AuNp NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe ____ ____ ",
  "nD":"____ MnHg CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____ ",
  "nA":"____ TiPb FeCu HgMn ____ ____ MnHg CuFe ____ ____ AuNp NpAu ",
  "nE":"CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____ MnHg ",
  "nB":"FeCu HgMn ____ ____ MnHg CuFe ____ ____ AuNp NpAu ____ TiPb "},

 {"$T":"k26",
  "nF":"PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____ ____ MnHg CuFe ",
  "nC":"HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ____ ____ TiPb FeCu ",
  "nG":"AuNp ____ ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ",
  "nD":"____ MnHg CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____ ",
  "nA":"____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ____ ",
  "nE":"CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____ ____ MnHg ",
  "nB":"FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ____ ____ TiPb "},

 {"$T":"k256",
  "nF":"PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe ",
  "nC":"HgMn ____ ____ MnHg CuFe PbTi ____ ____ NpAu ____ TiPb FeCu ",
  "nG":"____ NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ",
  "nD":"____ MnHg CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____ ",
  "nA":"____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ____ NpAu ",
  "nE":"CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____ ____ MnHg ",
  "nB":"FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ____ NpAu ____ TiPb "},

 {"$T":"n0",
  "nF":"PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____ CuHg ",
  "nC":"HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____ FePb ",
  "nG":"AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____ CuHg PbFe ____ ",
  "nD":"SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____ ",
  "nA":"AgAu ____ FePb HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____ ",
  "nE":"CuHg PbFe ____ AuAg ____ AgAu ____ FePb HgCu ____ SnSn ____ ",
  "nB":"FePb HgCu ____ SnSn ____ CuHg PbFe ____ AuAg ____ AgAu ____ "},

 {"$T":"j5",
  "nF":"TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____ AuSn ____ AgHg ",
  "nC":"PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____ CuPb ",
  "nG":"____ ____ SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ",
  "nD":"AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____ ",
  "nA":"SnAu ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____ ",
  "nE":"AgHg TiFe FeTi ____ ____ SnAu ____ CuPb PbCu ____ AuSn ____ ",
  "nB":"CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ____ ____ SnAu ____ "},

 {"$T":"k34",
  "nF":"TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____ ____ ",
  "nC":"PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____ CuPb ",
  "nG":"HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe FeTi ",
  "nD":"AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ",
  "nA":"SnAu ____ CuPb PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____ ",
  "nE":"____ TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ AuSn ____ ",
  "nB":"CuPb PbCu ____ AuSn ____ ____ TiFe FeTi HgAg ____ SnAu ____ "},

 {"$T":"j5y6",
  "nF":"TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____ AgHg ",
  "nC":"PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____ CuPb ",
  "nG":"HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi ",
  "nD":"AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____ ",
  "nA":"____ ____ CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____ ",
  "nE":"AgHg TiFe FeTi HgAg ____ ____ ____ CuPb PbCu ____ AuSn ____ ",
  "nB":"CuPb PbCu ____ AuSn ____ AgHg TiFe FeTi HgAg ____ ____ ____ "},

 {"$T":"k34x2",
  "nF":"TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____ AgHg ",
  "nC":"PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb ",
  "nG":"HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe FeTi ",
  "nD":"____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ",
  "nA":"SnAu ____ CuPb PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____ ",
  "nE":"AgHg TiFe FeTi HgAg ____ SnAu ____ CuPb PbCu ____ ____ ____ ",
  "nB":"CuPb PbCu ____ ____ ____ AgHg TiFe FeTi HgAg ____ SnAu ____ "},

 {"$T":"k1",
  "nF":"UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____ SnHg ",
  "nC":"____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ",
  "nG":"PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe ____ ",
  "nD":"HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr ",
  "nA":"AuAu ____ AgPb ____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____ ",
  "nE":"SnHg UrFe ____ PbAg ____ AuAu ____ AgPb ____ FeUr HgSn ____ ",
  "nB":"AgPb ____ FeUr HgSn ____ SnHg UrFe ____ PbAg ____ AuAu ____ "},

 {"$T":"k17j5",
  "nF":"MnFe CuTi ____ ____ AuAu ____ ____ TiCu FeMn HgSn ____ SnHg ",
  "nC":"TiCu FeMn HgSn ____ SnHg MnFe CuTi ____ ____ AuAu ____ ____ ",
  "nG":"____ ____ AuAu ____ ____ TiCu FeMn HgSn ____ SnHg MnFe CuTi ",
  "nD":"HgSn ____ SnHg MnFe CuTi ____ ____ AuAu ____ ____ TiCu FeMn ",
  "nA":"AuAu ____ ____ TiCu FeMn HgSn ____ SnHg MnFe CuTi ____ ____ ",
  "nE":"SnHg MnFe CuTi ____ ____ AuAu ____ ____ TiCu FeMn HgSn ____ ",
  "nB":"____ TiCu FeMn HgSn ____ SnHg MnFe CuTi ____ ____ AuAu ____ "},

 {"$T":"j2k34",
  "nF":"MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____ ____ ",
  "nC":"TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____ AuAu ____ AgPb ",
  "nG":"PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe CuTi ",
  "nD":"____ ____ ____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ",
  "nA":"AuAu ____ AgPb TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____ ",
  "nE":"____ MnFe CuTi PbAg ____ AuAu ____ AgPb TiCu FeMn ____ ____ ",
  "nB":"AgPb TiCu FeMn ____ ____ ____ MnFe CuTi PbAg ____ AuAu ____ "},

 {"$T":"n25x6",
  "nF":"MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____ ____ ",
  "nC":"TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____ AgPb ",
  "nG":"PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi ",
  "nD":"HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ",
  "nA":"____ ____ AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____ ",
  "nE":"____ MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn HgSn ____ ",
  "nB":"AgPb TiCu FeMn HgSn ____ ____ MnFe CuTi PbAg ____ ____ ____ "},

 {"$T":"j25y6",
  "nF":"MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____ SnHg ",
  "nC":"TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____ ____ ____ AgPb ",
  "nG":"PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi ",
  "nD":"____ ____ SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ",
  "nA":"____ ____ AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____ ",
  "nE":"SnHg MnFe CuTi PbAg ____ ____ ____ AgPb TiCu FeMn ____ ____ ",
  "nB":"AgPb TiCu FeMn ____ ____ SnHg MnFe CuTi PbAg ____ ____ ____ "},

 {"$T":"k5",
  "nF":"NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____ AuHg ",
  "nC":"UrCu ____ PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ",
  "nG":"____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ",
  "nD":"PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ____ ",
  "nA":"HgAu ____ SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ____ FeNp ",
  "nE":"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb UrCu ____ PbSn ____ ",
  "nB":"SnPb UrCu ____ PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ "},

 {"$T":"k15",
  "nF":"NpFe ____ ____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____ AuHg ",
  "nC":"____ CuUr PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ",
  "nG":"____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ",
  "nD":"PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____ CuUr ",
  "nA":"HgAu ____ SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ____ FeNp ",
  "nE":"AuHg NpFe ____ ____ FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ",
  "nB":"SnPb ____ CuUr PbSn ____ AuHg NpFe ____ ____ FeNp HgAu ____ "},

 {"$T":"j56",
  "nF":"NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ____ PbSn ____ AuHg ",
  "nC":"UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____ SnPb ",
  "nG":"____ FeNp ____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ",
  "nD":"PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ____ ",
  "nA":"____ ____ SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ",
  "nE":"AuHg NpFe AgTi ____ FeNp ____ ____ SnPb UrCu ____ PbSn ____ ",
  "nB":"SnPb UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ____ ____ "},

 {"$T":"k135x4",
  "nF":"NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ____ ",
  "nC":"____ CuUr PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____ SnPb ",
  "nG":"TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe ____ ",
  "nD":"PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr ",
  "nA":"HgAu ____ SnPb ____ CuUr PbSn ____ ____ NpFe ____ TiAg FeNp ",
  "nE":"____ NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr PbSn ____ ",
  "nB":"SnPb ____ CuUr PbSn ____ ____ NpFe ____ TiAg FeNp HgAu ____ "},

 {"$T":"j56y7",
  "nF":"NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ____ PbSn ____ AuHg ",
  "nC":"UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____ ____ ",
  "nG":"____ FeNp HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe AgTi ",
  "nD":"PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ____ ",
  "nA":"HgAu ____ ____ UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp ",
  "nE":"AuHg NpFe AgTi ____ FeNp HgAu ____ ____ UrCu ____ PbSn ____ ",
  "nB":"____ UrCu ____ PbSn ____ AuHg NpFe AgTi ____ FeNp HgAu ____ "},

 {"$T":"n345y7",
  "nF":"NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____ AuHg ",
  "nC":"____ CuUr ____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ",
  "nG":"TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe ____ ",
  "nD":"____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr ",
  "nA":"HgAu ____ SnPb ____ CuUr ____ ____ AuHg NpFe ____ TiAg FeNp ",
  "nE":"AuHg NpFe ____ TiAg FeNp HgAu ____ SnPb ____ CuUr ____ ____ ",
  "nB":"SnPb ____ CuUr ____ ____ AuHg NpFe ____ TiAg FeNp HgAu ____ "},

 {"$T":"k1j6y7",
  "nF":"NpFe ____ TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____ AuHg ",
  "nC":"____ CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ",
  "nG":"TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe ____ ",
  "nD":"PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____ CuUr ",
  "nA":"HgAu ____ ____ ____ CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp ",
  "nE":"AuHg NpFe ____ TiAg FeNp HgAu ____ ____ ____ CuUr PbSn ____ ",
  "nB":"____ ____ CuUr PbSn ____ AuHg NpFe ____ TiAg FeNp HgAu ____ "},

 {"$T":"k345x2",
  "nF":"NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ____ ____ AuHg ",
  "nC":"UrCu ____ ____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb ",
  "nG":"____ FeNp HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ",
  "nD":"____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ",
  "nA":"HgAu ____ SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ____ FeNp ",
  "nE":"AuHg NpFe AgTi ____ FeNp HgAu ____ SnPb UrCu ____ ____ ____ ",
  "nB":"SnPb UrCu ____ ____ ____ AuHg NpFe AgTi ____ FeNp HgAu ____ "},

 {"$T":"k2j56y7",
  "nF":"PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ____ ____ FePu HgHg ",
  "nC":"NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____ ____ ",
  "nG":"____ CuNp PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe SnTi ",
  "nD":"____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ____ ",
  "nA":"PbAu ____ ____ NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp ",
  "nE":"HgHg PuFe SnTi ____ CuNp PbAu ____ ____ NpCu ____ ____ FePu ",
  "nB":"____ NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp PbAu ____ "},

 {"$T":"j346y5",
  "nF":"PuFe ____ ____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu HgHg ",
  "nC":"NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____ AuPb ",
  "nG":"____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ",
  "nD":"TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu ____ ",
  "nA":"____ ____ AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp ",
  "nE":"HgHg PuFe ____ ____ CuNp ____ ____ AuPb NpCu ____ TiSn FePu ",
  "nB":"AuPb NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp ____ ____ "},

 {"$T":"j3k5",
  "nF":"PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ____ ",
  "nC":"NpCu ____ TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____ AuPb ",
  "nG":"____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe ____ ",
  "nD":"TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ ",
  "nA":"PbAu ____ AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____ CuNp ",
  "nE":"____ PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ TiSn FePu ",
  "nB":"AuPb NpCu ____ TiSn FePu ____ PuFe ____ ____ CuNp PbAu ____ "},

 {"$T":"n167",
  "nF":"PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ____ ",
  "nC":"NpCu ____ ____ FePu ____ PuFe SnTi ____ CuNp PbAu ____ AuPb ",
  "nG":"____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe SnTi ",
  "nD":"____ FePu ____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ",
  "nA":"PbAu ____ AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____ CuNp ",
  "nE":"____ PuFe SnTi ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ",
  "nB":"AuPb NpCu ____ ____ FePu ____ PuFe SnTi ____ CuNp PbAu ____ "},

 {"$T":"k2",
  "nF":"PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePb HgHg ",
  "nC":"NpCu ____ ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ",
  "nG":"UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ ",
  "nD":"____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ____ ",
  "nA":"PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ UrAg ____ ",
  "nE":"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb NpCu ____ ____ FePu ",
  "nB":"AuPb NpCu ____ ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ "},

 {"$T":"k125",
  "nF":"PuFe ____ ____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu HgHg ",
  "nC":"____ AgUr ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ",
  "nG":"____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ ",
  "nD":"____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ AgUr ",
  "nA":"PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____ CuNp ",
  "nE":"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ AgUr ____ FePu ",
  "nB":"AuPb ____ AgUr ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ "},

 {"$T":"k25",
  "nF":"PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePb HgHg ",
  "nC":"NpCu ____ ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ",
  "nG":"____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ ",
  "nD":"____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ ",
  "nA":"PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____ CuNp ",
  "nE":"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb NpCu ____ ____ FePu ",
  "nB":"AuPb NpCu ____ ____ FePu HgHg PuFe ____ ____ CuNp PbAu ____ "},

 {"$T":"k12",
  "nF":"PuFe ____ UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg ",
  "nC":"____ AgUr ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ",
  "nG":"UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ ",
  "nD":"____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ AgUr ",
  "nA":"PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg ____ ",
  "nE":"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ AgUr ____ FePu ",
  "nB":"AuPb ____ AgUr ____ FePu HgHg PuFe ____ UrAg ____ PbAu ____ "},

 {"$T":"k12j5",
  "nF":"PuFe SnTi ____ ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg ",
  "nC":"____ AgUr ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ",
  "nG":"____ ____ PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ",
  "nD":"____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ AgUr ",
  "nA":"PbAu ____ AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____ ____ ",
  "nE":"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ AgUr ____ FePu ",
  "nB":"AuPb ____ AgUr ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ "},

 {"$T":"k2x1",
  "nF":"PuFe ____ UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg ",
  "nC":"____ ____ TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ",
  "nG":"UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ ",
  "nD":"TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ____ ",
  "nA":"PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg ____ ",
  "nE":"HgHg PuFe ____ UrAg ____ PbAu ____ AuPb ____ ____ TiSn FePu ",
  "nB":"AuPb ____ ____ TiSn FePu HgHg PuFe ____ UrAg ____ PbAu ____ "},

 {"$T":"k2j5",
  "nF":"PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg ",
  "nC":"NpCu ____ ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ",
  "nG":"____ ____ PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ",
  "nD":"____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ____ ",
  "nA":"PbAu ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ ____ ",
  "nE":"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb NpCu ____ ____ FePu ",
  "nB":"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ ____ PbAu ____ "},

 {"$T":"k25x1",
  "nF":"PuFe ____ ____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu HgHg ",
  "nC":"____ ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ",
  "nG":"____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ ",
  "nD":"TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ____ ",
  "nA":"PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____ CuNp ",
  "nE":"HgHg PuFe ____ ____ CuNp PbAu ____ AuPb ____ ____ TiSn FePu ",
  "nB":"AuPb ____ ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ "},

 {"$T":"k2j56",
  "nF":"PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ____ ____ FePu HgHg ",
  "nC":"NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp ____ ____ AuPb ",
  "nG":"____ CuNp ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ",
  "nD":"____ FePu HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ____ ",
  "nA":"____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp ",
  "nE":"HgHg PuFe SnTi ____ CuNp ____ ____ AuPb NpCu ____ ____ FePu ",
  "nB":"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ____ CuNp ____ ____ "},

 {"$T":"k257x1",
  "nF":"PuFe ____ ____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu HgHg ",
  "nC":"NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ ",
  "nG":"____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe ____ ",
  "nD":"TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu ____ ",
  "nA":"PbAu ____ ____ NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp ",
  "nE":"HgHg PuFe ____ ____ CuNp PbAu ____ ____ NpCu ____ TiSn FePu ",
  "nB":"____ NpCu ____ TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ "},

 {"$T":"k2j5y6",
  "nF":"PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu HgHg ",
  "nC":"NpCu ____ ____ FePu HgHg PuFe SnTi UrAg ____ ____ ____ AuPb ",
  "nG":"UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi ",
  "nD":"____ FePu HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ____ ",
  "nA":"____ ____ AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg ____ ",
  "nE":"HgHg PuFe SnTi UrAg ____ ____ ____ AuPb NpCu ____ ____ FePu ",
  "nB":"AuPb NpCu ____ ____ FePu HgHg PuFe SnTi UrAg ____ ____ ____ "},

 {"$T":"k25x17",
  "nF":"PuFe ____ ____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu HgHg ",
  "nC":"____ AgUr TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ ",
  "nG":"____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe ____ ",
  "nD":"TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____ AgUr ",
  "nA":"PbAu ____ ____ ____ AgUr TiSn FePu HgHg PuFe ____ ____ CuNp ",
  "nE":"HgHg PuFe ____ ____ CuNp PbAu ____ ____ ____ AgUr TiSn FePu ",
  "nB":"____ ____ AgUr TiSn FePu HgHg PuFe ____ ____ CuNp PbAu ____ "},

 {"$T":"k2j5x1",
  "nF":"PuFe SnTi ____ ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg ",
  "nC":"____ ____ TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ",
  "nG":"____ ____ PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ",
  "nD":"TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ____ ",
  "nA":"PbAu ____ AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____ ____ ",
  "nE":"HgHg PuFe SnTi ____ ____ PbAu ____ AuPb ____ ____ TiSn FePu ",
  "nB":"AuPb ____ ____ TiSn FePu HgHg PuFe SnTi ____ ____ PbAu ____ "},

 {"$T":"k1j5",
  "nF":"FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr NpSn ____ TiHg ",
  "nC":"____ AuUr NpSn ____ TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ",
  "nG":"____ ____ UrAu ____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ",
  "nD":"NpSn ____ TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr ",
  "nA":"UrAu ____ PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____ ____ ",
  "nE":"TiHg FeFe HgTi ____ ____ UrAu ____ PbPb ____ AuUr NpSn ____ ",
  "nB":"PbPb ____ AuUr NpSn ____ TiHg FeFe HgTi ____ ____ UrAu ____ "},

 {"$T":"n67x2",
  "nF":"FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ____ ____ TiHg ",
  "nC":"____ AuUr ____ ____ TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ",
  "nG":"____ SnNp UrAu ____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ",
  "nD":"____ ____ TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ",
  "nA":"UrAu ____ PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____ SnNp ",
  "nE":"TiHg FeFe HgTi ____ SnNp UrAu ____ PbPb ____ AuUr ____ ____ ",
  "nB":"PbPb ____ AuUr ____ ____ TiHg FeFe HgTi ____ SnNp UrAu ____ "},

 {"$T":"k1j56y7",
  "nF":"FeFe HgTi ____ SnNp UrAu ____ ____ ____ AuUr NpSn ____ TiHg ",
  "nC":"____ AuUr NpSn ____ TiHg FeFe HgTi ____ SnNp UrAu ____ ____ ",
  "nG":"____ SnNp UrAu ____ ____ ____ AuUr NpSn ____ TiHg FeFe HgTi ",
  "nD":"NpSn ____ TiHg FeFe HgTi ____ SnNp UrAu ____ ____ ____ AuUr ",
  "nA":"UrAu ____ ____ ____ AuUr NpSn ____ TiHg FeFe HgTi ____ SnNp ",
  "nE":"TiHg FeFe HgTi ____ SnNp UrAu ____ ____ ____ AuUr NpSn ____ ",
  "nB":"____ ____ AuUr NpSn ____ TiHg FeFe HgTi ____ SnNp UrAu ____ "},

 {"$T":"j2k5",
  "nF":"CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____ MnHg ",
  "nC":"FeCu HgMn ____ ____ MnHg CuFe ____ ____ AuNp NpAu ____ TiPb ",
  "nG":"____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe ____ ",
  "nD":"____ ____ MnHg CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ",
  "nA":"NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe ____ ____ AuNp ",
  "nE":"MnHg CuFe ____ ____ AuNp NpAu ____ TiPb FeCu HgMn ____ ____ ",
  "nB":"TiPb FeCu HgMn ____ ____ MnHg CuFe ____ ____ AuNp NpAu ____ "},

 {"$T":"n6x2",
  "nF":"CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____ ____ MnHg ",
  "nC":"FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp NpAu ____ ____ ",
  "nG":"____ AuNp NpAu ____ ____ FeCu HgMn ____ ____ MnHg CuFe PbTi ",
  "nD":"____ ____ MnHg CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ",
  "nA":"NpAu ____ ____ FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ",
  "nE":"MnHg CuFe PbTi ____ AuNp NpAu ____ ____ FeCu HgMn ____ ____ ",
  "nB":"____ FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp NpAu ____ "},

 {"$T":"j25",
  "nF":"CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____ ____ MnHg ",
  "nC":"FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ____ NpAu ____ TiPb ",
  "nG":"____ ____ NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ",
  "nD":"____ ____ MnHg CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ",
  "nA":"NpAu ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ____ ",
  "nE":"MnHg CuFe PbTi ____ ____ NpAu ____ TiPb FeCu HgMn ____ ____ ",
  "nB":"TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ ____ NpAu ____ "},

 {"$T":"j256",
  "nF":"CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____ ____ MnHg ",
  "nC":"FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ____ ____ TiPb ",
  "nG":"____ AuNp ____ ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ",
  "nD":"____ ____ MnHg CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ",
  "nA":"____ ____ TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ",
  "nE":"MnHg CuFe PbTi ____ AuNp ____ ____ TiPb FeCu HgMn ____ ____ ",
  "nB":"TiPb FeCu HgMn ____ ____ MnHg CuFe PbTi ____ AuNp ____ ____ "}

];

